[application]
asset_dir = "public"
default_platform = "web"
name = "dioxus-prototype"
out_dir = "dist"

[application.plugins]
available = true
required = []

[bundler]
category = "Utility"
copyright = "Copyright 2022-2025 CroftSoft Inc"
icon = ["icons/icon.png"]
identifier = "com.croftsoft.app.dioxus-prototype"
long_description = """
CroftSoft Dioxus Prototype
"""
publisher = "dioxus-prototype"
resources = ["public/*"]
short_description = "CroftSoft Dioxus Prototype"

[web.app]
title = "CroftSoft Dioxus Prototype"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
script = []
style = []

[web.resource.dev]
script = []
